version: "3.7"

services:
  sfu:
    image: pionwebrtc/ion-sfu:latest
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    volumes:
      - "./configs/docker/sfu_local.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet

  biz:
    image: pionwebrtc/ion-biz:latest
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    volumes:
      - "./configs/docker/biz_local.toml:/configs/biz.toml"
    ports:
      - 8443:8443
    networks:
      - ionnet
    depends_on:
      - nats
      - etcd

  islb:
    image: pionwebrtc/ion-islb:latest
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    volumes:
      - "./configs/docker/islb_local.toml:/configs/islb.toml"
    depends_on:
      - nats
      - etcd
      - redis
    networks:
      - ionnet

  nats:
    image: nats
    ports:
      - 4223:4222
    networks:
      - ionnet

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.9
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    expose:
      - 2379
    ports:
      - 2389:2379
      - 8011:2379
      - 8012:2380
    networks:
      - ionnet

  redis:
    image: redis:5.0.9
    container_name: redis
    hostname: redis
    expose:
      - 6379
    ports:
      - 6380:6379
      - 6379:6379
    networks:
      - ionnet

  redis_commander:
    image: "rediscommander/redis-commander"
    restart: always
    depends_on:
      - redis
    environment:
    - REDIS_HOST=redis
    ports:
      - "8085:8081"
    networks:
      - ionnet

  # etcd_browser:
  #   image: buddho/etcd-browser
  #   ports:
  #     - 8006:8000
  #   depends_on:
  #     - etcd
  #   environment:
  #     ETCD_HOST: "localhost"
  #     ETCD_PORT: "2389"
  #   networks:
  #     - ionnet

  etcd_lucas:
    image: registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2
    environment:
      ENDPOINTS: "http://etcd:2379"
    ports:
      - 8088:8080
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
