version: "3.7"

services:
  biz:
    image: pionwebrtc/ion:v1.5.3-biz
    volumes:
      - "./configs/certs:/configs/certs"
    ports:
      - 8443:8443
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet

  sfu:
    image: pionwebrtc/ion:v1.5.3-sfu
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet

  avp:
    image: pionwebrtc/ion:v1.5.3-avp
    depends_on:
      - nats
      - etcd
    networks:
      - ionnet


  islb:
    image: pionwebrtc/ion:v1.5.3-islb
    depends_on:
      - nats
      - etcd
      - redis
    networks:
      - ionnet

  nats:
    image: nats
    networks:
      - ionnet

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.14
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    networks:
      - ionnet

  redis:
    image: redis:6.0.9
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
