[global]
#pprof = ":6061"

# data center id
dc = "dc1"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["livespot-ion-etcd-production:2379"]

[nats]
url = "nats://livespot-ion-nats-production:4222"

[redis]
addrs = ["livespot-ion-redis-production:6379"]
password = ""
db = 0
