[global]
pprof = ":6061"

# data center id
dc = "dc1"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["caves-ion-etcd-production:2379"]

[nats]
url = "nats://caves-ion-nats-production:4222"

[redis]
addrs = ["caves-ion-redis-production:6379"]
password = ""
db = 0
